### ISSUE TITLE
MAJOR mobile issues

### ISSUE THREAD

**Issue by Mhdtarek** [Empire-of-Man/website#2]
On iPhone 11 there are two current issues, the first one is that it's not displaying the full slogan. Instead of "Turning boys into men" it was "Turning boys into".
The second one is that the image is weird 
![bild](https://user-images.githubusercontent.com/99592820/235342086-2edb29f8-e6f9-461e-b82a-c3de92cb2cdc.png)

todo 
- [ ] Fix image for mobile and desktop
- [ ] Fix slogan issue 
- [ ] Fix alignment

**Comment by Mhdtarek** [comment]
Ill finish this this week

**Comment by 10407dev** [comment]
He didn't finish it this week

**Comment by Mhdtarek** [comment]
> He didn't finish it this week

Finished it
